@startuml
hide circle
skinparam classAttributeIconSize 0

Class "<<interface>>\nParser" as Parser
Class RemarkCommandParser {
  +parse(): RemarkCommand
}
Class RemarkParserException

RemarkCommandParser .up.|> Parser
Parser .right.> RemarkParserException: throws >
RemarkCommandParser .right.> RemarkParserException: throws >
@enduml
